### ISSUE TITLE
I am able to delete category that's not mine

### ISSUE THREAD

**Issue by vojkovoga** [kuderluka/notes_laravel#30]
I added a note to category that's not mine and now I can see category under "Your categories" and I can delete it.

**Comment by kuderluka** [comment]
I added that as a feature of my program. The code works in such a way that if you delete the category that you are not an owner of you are removed from the list of its users, with the category still remaining in the database. The messaging regarding that has been updated in #32

**Comment by vojkovoga** [comment]
I understand but it's confusing for user. I didn't know how code works and pretty sure other user won't either. Present different command then "Delete" or some other feature that user know it will have different functionality.

**Comment by kuderluka** [comment]
This has been fixed in #45
